version: '3.8'

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-rc
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb

  app:
    depends_on:
      - influxdb
    environment:
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      INFLUX2_URL: http://influxdb:8086
      INFLUX2_TOKEN_FILE: /run/secrets/influx2_token
    volumes:
      - sqlite_data:/data
    secrets:
      - discord_token
      - influx2_token

volumes:
  influx_data:
  sqlite_data:

secrets:
  discord_token:
    file: discord_token.txt
  influx2_token:
    file: influx2_token.txt

