version: '3.8'

services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    ports:
      - "9999:9999"
    volumes:
      - influx_data:/var/lib/influxdb

  app:
    depends_on:
      - influxdb
    build: .
    image: laplace_app
    environment:
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      INFLUX_URL: influxdb:9999
      INFLUX_ORG: tph
      INFLUX_BUCKET: laplace
      INFLUX_TOKEN_FILE: /run/secrets/influx_token
    volumes:
      - sqlite_data:/data
    secrets:
      - discord_token
      - influx_token
    configs:
      - app_config

volumes:
  influx_data:
  sqlite_data:

secrets:
  discord_token:
    file: discord_token.txt
  influx_token:
    file: influx_token.txt

configs:
  app_config:
    file: application.conf
